resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: quay.io/medik8s/storage-based-remediation-operator
  newTag: latest
patches:
- patch: |
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: RELATED_IMAGE_AGENT
        value: ${AGENT_IMG}
  target:
    kind: Deployment
    name: controller-manager
